version: '3'
services:
  nginx:
    image: library/nginx:1.18-alpine
    volumes:
    - ./dist:/usr/share/nginx/html:ro
    ports:
    - 8080:80
  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-20200525
    ports:
    - 4444:4444
    - 5900:5900
    volumes:
      - /dev/shm:/dev/shm

