[build]
  publish = "public"
  command = "npm run build && npm run sentry_release"


# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.master]
  [context.master.environment]
    ENVIRONMENT = "production"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
#[context.deploy-preview.environment]
#  ACCESS_TOKEN = "not so secret"
