[build]
  publish = "public"
  command = "yarn run build"


# Production context: All deploys to the main
# repository branch will inherit these settings.
#[context.master]
#  command = "yarn run build"
#  [context.master.environment]
#    ACCESS_TOKEN = "super secret"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
#[context.deploy-preview.environment]
#  ACCESS_TOKEN = "not so secret"